---
name: main

on:
  push:
    branches: [ v2, v3 ]
  pull_request:
    branches: [ v2, v3 ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - uses: actions/setup-go@v5
      with:
        go-version: 1.26.x
      id: go

    - name: 'Run tests'
      run: |
        go test -v ./...

    - name: 'Build samples'
      run: |
        ROOTDIR=$PWD
        cd examples/aws/
        go build -v
        cd $ROOTDIR/
        cd examples/gcp/
        go build -v
