---
name: main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    if: "!contains(github.event.commits[0].message, 'ci skip')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: ^1.13
      id: go

    - name: Run tests
      run: |
        go test -v ./...

    - name: Build samples
      run: |
        ROOTDIR=$PWD
        cd examples/aws/
        go build -v
        cd $ROOTDIR/
        cd examples/gcp/
        go build -v
